In [5]:
import pandas as pd

department_data_file_name = '직원명부.xlsx'
sh_match_department_staffer = pd.read_excel(department_data_file_name, sheet_name=0)
sh_match_department_staffer

,STATION,FIRSTNAME,LASTNAME,COMPANY,HOUSEPHONE,MOBILEPHONE,JOB,FAX,COMPANYPHONE,ADDRESS1,...,ZIP,EMAIL,NICKNAME,SPEEDNO,COUNTRY,MEMO,HOUSEPHONE.1,ACCOUNTNO,PHYSICALSTATION,PHONE_LEVEL
0,3000,NaN,김동일,시장실,시장,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,시장,010000000001,NaN,1
1,3001,NaN,김세준,시장실,비서실장,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,비서실장,010000000001,NaN,1
2,3002,NaN,김세준,시장실,비서실장,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,비서실장,010000000001,NaN,1
3,3003,NaN,조경진,시장실,수행비서,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,수행비서,010000000001,NaN,1
4,3004,NaN,김민혜,시장실,부속실,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,비서,010000000001,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3796,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN